# Generated by Django 4.2 on 2024-05-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'В ожидании'), ('Accepted', 'Принято'), ('Rejected', 'Отклонено'), ('Successful', 'Успешно')], default='Pending', max_length=10),
        ),
    ]
