# Generated by Django 4.2 on 2024-05-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_project_deadline_alter_application_date_pub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Open', 'Открыт'), ('Progress', 'В процессе'), ('Closed', 'Закрыт')], default='Open', max_length=10, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
