# Generated by Django 4.2 on 2024-05-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='successful_projects',
            field=models.IntegerField(blank=True, max_length=9, null=True),
        ),
    ]
